name: Terraform Deployment with Checkov

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Update and install dependencies
      - name: Update system and install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo rm -rf awscliv2.zip aws

      # Step 3: Configure AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Step 5: Install Checkov
      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade checkov

      # Step 6: Run Checkov to scan Terraform code
      - name: Run Checkov scan
        run: checkov -d .
        continue-on-error: true

      # Step 7: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 8: Validate Terraform files
      - name: Terraform Validate
        run: terraform validate

      # Step 9: Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan

      # Step 10: Apply Terraform deployment
      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform apply -auto-approve tfplan
