name: 'Terraform Infrastructure Deployment with Checkov Scan'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  TF_VAR_region: us-east-1

jobs:
  build:
    name: Build and Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Cài đặt Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # 3. Cài đặt Checkov để kiểm tra bảo mật và tuân thủ của mã Terraform
      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      # 4. Chạy Checkov để kiểm tra mã Terraform
      - name: Checkov - Static Code Analysis on EC2 Module
        run: checkov -d modules/ec2

      - name: Checkov - Static Code Analysis on Route Table Module
        run: checkov -d modules/route_table

      - name: Checkov - Static Code Analysis on VPC Module
        run: checkov -d modules/vpc

      - name: Checkov - Static Code Analysis on NAT Gateway Module
        run: checkov -d modules/nat_gateway

      - name: Checkov - Static Code Analysis on Security Group Module
        run: checkov -d modules/security_group

      - name: Checkov - Static Code Analysis on Subnet Module
        run: checkov -d modules/subnet

      # 5. Khởi tạo Terraform
      - name: Terraform init
        id: init
        run: terraform init

      # 6. Tạo kế hoạch triển khai Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # 7. Áp dụng kế hoạch Terraform để triển khai cơ sở hạ tầng
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve tfplan
